name: HarderSurvival
version: ${project.version}
main: me.moob.hardersurvival.Main
api-version: 1.16
authors: [ moob ]
description: a mod that makes survival harder, mobs stronger, and food less good
